remote_theme: 42bv/fortytwo
title: 'react-spring-enums'
description: 'Sharing enums with a Java Spring Boot back-end'
baseurl: /react-spring-enums/
aux_links:
  'View on GitHub':
    - '//github.com/42bv/react-spring-enums'
plugins:
  - jekyll-remote-theme
